#!/bin/sh

bash ./schema-uninstall

rm "/usr/local/bin/minifier"

rm "/usr/share/icons/hicolor/16x16/apps/minifier.png"
rm "/usr/share/icons/hicolor/48x48/apps/minifier.png"
rm "/usr/share/icons/hicolor/scalable/apps/minifier.svg"

# NB: user-specific  ~/.local/share/applications has been a flop for me
rm "/usr/share/applications/uk.co.archaicgroves.minifier.desktop"
gtk-update-icon-cache /usr/share/icons/hicolor/
